### ISSUE TITLE
verwijderen dataset met notificatie werkt niet

### ISSUE THREAD

**Issue by copierrj** [IDgis/geo-publisher-test#66]
Het is niet mogelijk om een dataset met een structuurwijzigingsnotificatie te verwijderen. 

Gemeld door: @andreweijmer
CC: @HermanAssink 

Informatie in de logfile: 

08:28:06.407 ERROR n.idgis.publisher.admin.DatasetAdmin - failure: 16abaefc-ac39-46da-96e4-bfad5bc9834b java.util.concurrent.CompletionException: java.lang.RuntimeEx
ception: com.mysema.query.QueryException: Caught PSQLException for delete from publisher.job
where exists (select 1
from publisher.import_job import_job
join publisher.dataset dataset
on import_job.dataset_id = dataset.id
where import_job.job_id = job.id and dataset.identification = ?)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1954)
        at nl.idgis.publisher.utils.FutureUtils$2.onComplete(FutureUtils.java:518)
        at akka.dispatch.OnComplete.internal(Future.scala:247)
        at akka.dispatch.OnComplete.internal(Future.scala:244)
        at akka.dispatch.japi$CallbackBridge.apply(Future.scala:174)
        at akka.dispatch.japi$CallbackBridge.apply(Future.scala:171)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: com.mysema.query.QueryException: Caught PSQLException for delete from publisher.job
where exists (select 1
from publisher.import_job import_job
join publisher.dataset dataset
on import_job.dataset_id = dataset.id
where import_job.job_id = job.id and dataset.identification = ?)
        at nl.idgis.publisher.database.AbstractAsyncSQLClause.lambda$static$0(AbstractAsyncSQLClause.java:14)
        at nl.idgis.publisher.database.AbstractAsyncSQLClause$$Lambda$15/1829264908.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 21 more
Caused by: com.mysema.query.QueryException: Caught PSQLException for delete from publisher.job
where exists (select 1
from publisher.import_job import_job
join publisher.dataset dataset
on import_job.dataset_id = dataset.id
where import_job.job_id = job.id and dataset.identification = ?)
        at com.mysema.query.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:38)
        at com.mysema.query.sql.Configuration.translate(Configuration.java:434)
        at com.mysema.query.sql.dml.SQLDeleteClause.execute(SQLDeleteClause.java:161)
        at nl.idgis.publisher.database.PublisherTransaction.executePerformDelete(PublisherTransaction.java:222)
        at nl.idgis.publisher.database.PublisherTransaction.executeQuery(PublisherTransaction.java:171)
        at nl.idgis.publisher.database.JdbcTransaction.lambda$handleQuery$22(JdbcTransaction.java:144)
        at nl.idgis.publisher.database.JdbcTransaction$$Lambda$12/303569008.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "job" violates foreign key constraint "notification_job_id_fkey" on table "notification"
  Detail: Key (id)=(3050) is still referenced from table "notification".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334)
        at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
        at com.mysema.query.sql.dml.SQLDeleteClause.execute(SQLDeleteClause.java:155)
        ... 7 more

**Comment by andreweijmer** [comment]
Klopt. maar wat doe je dan als de dataset op ingepland blijft staan en de structuurwijziging niet wordt uitgevoerd?

**Comment by copierrj** [comment]
Kan op dit moment vanuit de beheerinterface niets aan gedaan worden. Zal ik het desbetreffende dataset met de hand uit de database verwijderen?

**Comment by andreweijmer** [comment]
Dat zou fijn zijn.

**Comment by copierrj** [comment]
dataset is verwijderd

**Comment by andreweijmer** [comment]
Ok. Service OV-B5 is nu ook weer correct gevuld.
kan echter nog geen nieuwe brongegevens als dataset toevoegen. Getracht het bestand "flora1900" als dataset te importeren. Deze komt niet in systeemtaaklijst te staan maar staat als dataset wel op ingepland.

Daarnaast staat er een import gepland "fietsroutenetwerk" . Deze is echter al ingeladen. 
kan op dit moment dus niet verder..

**Comment by andreweijmer** [comment]
heeft betrekking op productie
