### ISSUE TITLE
tiling werkt niet voor levels >= 11

### ISSUE THREAD

**Issue by copierrj** [IDgis/geo-publisher-test#71]
Het opvragen van niet gecachte tile leidt tot een foutsituatie:

(zie opmerking van @andreweijmer in #42)

```
java.lang.NullPointerException
    at org.geowebcache.storage.DefaultStorageBroker.getTransient(DefaultStorageBroker.java:92)
    at org.geowebcache.conveyor.ConveyorTile.retrieve(ConveyorTile.java:229)
    at org.geoserver.gwc.layer.GeoServerTileLayer.tryCacheFetch(GeoServerTileLayer.java:643)
    at org.geoserver.gwc.layer.GeoServerTileLayer.getMetatilingReponse(GeoServerTileLayer.java:498)
    at org.geoserver.gwc.layer.GeoServerTileLayer.getTile(GeoServerTileLayer.java:467)
    at org.geowebcache.GeoWebCacheDispatcher.handleServiceRequest(GeoWebCacheDispatcher.java:363)
    at org.geowebcache.GeoWebCacheDispatcher.handleRequestInternal(GeoWebCacheDispatcher.java:254)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.geoserver.gwc.dispatch.GwcServiceProxy.dispatch(GwcServiceProxy.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:792)
    at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:274)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
```

**Comment by copierrj** [comment]
Bug in geowebcache gefixed:

GeoWebCache/geowebcache#331
